export type FontCategory =
  | "all"
  | "bold"
  | "comic"
  | "retro"
  | "handwriting"
  | "elegant"
  | "news"
  | "modern";

export interface FontCategoryOption {
  id: FontCategory;
  label: string;
  icon: string;
  badgeText?: string;
}

export interface FontDefinition {
  id: string;
  name: string;
  family: string;
  category: Exclude<FontCategory, "all">;
  weights: number[];
  googleFontFamily?: string;
  license: string;
  tags: string[];
  description?: string;
  badge?: "Viral" | "Display" | "Comic" | "Retro" | "Script" | "Serif" | "News" | "Clean";
  fallback?: string;
}

export const FONT_CATEGORIES: FontCategoryOption[] = [
  { id: "all", label: "Semua", icon: "✨" },
  { id: "bold", label: "Bold / Viral", icon: "🔥", badgeText: "Viral" },
  { id: "comic", label: "Comic / Fun", icon: "🎨", badgeText: "Comic" },
  { id: "retro", label: "Retro", icon: "📻", badgeText: "Retro" },
  { id: "handwriting", label: "Handwriting", icon: "✍️", badgeText: "Script" },
  { id: "elegant", label: "Elegant", icon: "👑", badgeText: "Serif" },
  { id: "news", label: "News / Tight", icon: "📰", badgeText: "News" },
  { id: "modern", label: "Modern", icon: "⚡", badgeText: "Clean" },
];

export const FONT_CATALOG: FontDefinition[] = [
  // ----------------------------------------------------
  // BOLD / VIRAL (14 fonts)
  // ----------------------------------------------------
  {
    id: "anton",
    name: "Anton",
    family: "'Anton', sans-serif",
    category: "bold",
    weights: [400],
    googleFontFamily: "Anton",
    license: "OFL-1.1",
    tags: ["viral", "heavy", "youtube", "tiktok", "punchy", "bold", "sans"],
    description: "Sangat tegas, standar industri video viral TikTok & Reels.",
    badge: "Viral",
  },
  {
    id: "bangers",
    name: "Bangers",
    family: "'Bangers', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Bangers",
    license: "OFL-1.1",
    tags: ["comic", "shout", "punchy", "youtube", "pop", "bold"],
    description: "Karakter komik Amerika bertenaga tinggi untuk seruan/hook.",
    badge: "Viral",
  },
  {
    id: "bebas_neue",
    name: "Bebas Neue",
    family: "'Bebas Neue', sans-serif",
    category: "bold",
    weights: [400],
    googleFontFamily: "Bebas+Neue",
    license: "OFL-1.1",
    tags: ["headline", "clean", "condensed", "poster", "viral", "allcaps"],
    description: "Headline all-caps legendaris, rapi dan berwibawa.",
    badge: "Display",
  },
  {
    id: "bowlby_one_sc",
    name: "Bowlby One SC",
    family: "'Bowlby One SC', sans-serif",
    category: "bold",
    weights: [400],
    googleFontFamily: "Bowlby+One+SC",
    license: "OFL-1.1",
    tags: ["ultra", "poster", "solid", "block", "heavy"],
    description: "Blok tebal ekstra padat untuk kata kunci utama.",
    badge: "Display",
  },
  {
    id: "lilita_one",
    name: "Lilita One",
    family: "'Lilita One', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Lilita+One",
    license: "OFL-1.1",
    tags: ["chubby", "fun", "bold", "viral", "shortform"],
    description: "Tebal membulat yang ramah namun mencolok di layar kecil.",
    badge: "Viral",
  },
  {
    id: "luckiest_guy",
    name: "Luckiest Guy",
    family: "'Luckiest Guy', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Luckiest+Guy",
    license: "OFL-1.1",
    tags: ["punchy", "custom", "fun", "game", "viral"],
    description: "Font kartun ikonik dengan energi tinggi dan daya tarik instan.",
    badge: "Viral",
  },
  {
    id: "titan_one",
    name: "Titan One",
    family: "'Titan One', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Titan+One",
    license: "OFL-1.1",
    tags: ["heavy", "display", "titling", "friendly", "bold"],
    description: "Huruf besar montok yang sangat mudah terbaca di video cepat.",
    badge: "Display",
  },
  {
    id: "archivo_black",
    name: "Archivo Black",
    family: "'Archivo Black', sans-serif",
    category: "bold",
    weights: [400],
    googleFontFamily: "Archivo+Black",
    license: "OFL-1.1",
    tags: ["modern", "heavy", "block", "impact", "clean"],
    description: "Sans-serif modern super tebal untuk judul tegas.",
    badge: "Display",
  },
  {
    id: "black_ops_one",
    name: "Black Ops One",
    family: "'Black Ops One', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Black+Ops+One",
    license: "OFL-1.1",
    tags: ["military", "stencil", "gaming", "tactical", "action"],
    description: "Gaya militer stencil tajam untuk gaming dan alutsista.",
    badge: "Display",
  },
  {
    id: "passion_one",
    name: "Passion One",
    family: "'Passion One', cursive",
    category: "bold",
    weights: [700, 900],
    googleFontFamily: "Passion+One:wght@700;900",
    license: "OFL-1.1",
    tags: ["headline", "compact", "impact", "allcaps"],
    description: "Kompak dan berbobot tinggi untuk narasi dramatis.",
    badge: "Display",
  },
  {
    id: "fugaz_one",
    name: "Fugaz One",
    family: "'Fugaz One', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Fugaz+One",
    license: "OFL-1.1",
    tags: ["italic", "speed", "sport", "dynamic", "energy"],
    description: "Miring dinamis memberikan sensasi kecepatan dan energi olahraga.",
    badge: "Display",
  },
  {
    id: "righteous",
    name: "Righteous",
    family: "'Righteous', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Righteous",
    license: "OFL-1.1",
    tags: ["retro", "modern", "synthwave", "futuristic", "display"],
    description: "Gaya grid futuristik retro yang unik dan stand out.",
    badge: "Display",
  },
  {
    id: "shrikhand",
    name: "Shrikhand",
    family: "'Shrikhand', cursive",
    category: "bold",
    weights: [400],
    googleFontFamily: "Shrikhand",
    license: "OFL-1.1",
    tags: ["handpainted", "expressive", "curvy", "retro"],
    description: "Tipografi kuas lukis jalanan yang ekspresif dan berkarakter.",
    badge: "Display",
  },
  {
    id: "ultra",
    name: "Ultra",
    family: "'Ultra', serif",
    category: "bold",
    weights: [400],
    googleFontFamily: "Ultra",
    license: "OFL-1.1",
    tags: ["woodtype", "heavy", "western", "slab", "impact"],
    description: "Slab serif sangat tebal layaknya poster kayu vintage.",
    badge: "Display",
  },

  // ----------------------------------------------------
  // COMIC / FUN (12 fonts)
  // ----------------------------------------------------
  {
    id: "bungee",
    name: "Bungee",
    family: "'Bungee', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Bungee",
    license: "OFL-1.1",
    tags: ["signage", "blocky", "urban", "allcaps", "bold"],
    description: "Karakter plang toko urban yang kokoh dan penuh warna.",
    badge: "Comic",
  },
  {
    id: "bungee_shade",
    name: "Bungee Shade",
    family: "'Bungee Shade', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Bungee+Shade",
    license: "OFL-1.1",
    tags: ["3d", "shadow", "fun", "display", "arcade"],
    description: "Bungee dengan efek bayangan 3D retro arcade.",
    badge: "Comic",
  },
  {
    id: "bungee_inline",
    name: "Bungee Inline",
    family: "'Bungee Inline', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Bungee+Inline",
    license: "OFL-1.1",
    tags: ["inline", "display", "neon", "fun"],
    description: "Bungee dengan garis tengah dekoratif bergaya neon.",
    badge: "Comic",
  },
  {
    id: "chewy",
    name: "Chewy",
    family: "'Chewy', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Chewy",
    license: "OFL-1.1",
    tags: ["friendly", "candy", "casual", "fun", "bouncy"],
    description: "Lentur dan manis, pas untuk video komedi dan santai.",
    badge: "Comic",
  },
  {
    id: "fredoka",
    name: "Fredoka",
    family: "'Fredoka', sans-serif",
    category: "comic",
    weights: [600, 700],
    googleFontFamily: "Fredoka:wght@600;700",
    license: "OFL-1.1",
    tags: ["rounded", "modern", "clean", "friendly", "soft"],
    description: "Bulat sempurna, modern dan super bersih untuk subtitle kekinian.",
    badge: "Comic",
  },
  {
    id: "baloo_2",
    name: "Baloo 2",
    family: "'Baloo 2', cursive",
    category: "comic",
    weights: [700, 800],
    googleFontFamily: "Baloo+2:wght@700;800",
    license: "OFL-1.1",
    tags: ["bouncy", "soft", "friendly", "modern", "bold"],
    description: "Bentuk ceria dengan sentuhan tipografi kontemporer.",
    badge: "Comic",
  },
  {
    id: "coiny",
    name: "Coiny",
    family: "'Coiny', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Coiny",
    license: "OFL-1.1",
    tags: ["curly", "vernacular", "fun", "chubby"],
    description: "Garis membulat gemuk terinspirasi dari stiker pop.",
    badge: "Comic",
  },
  {
    id: "boogaloo",
    name: "Boogaloo",
    family: "'Boogaloo', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Boogaloo",
    license: "OFL-1.1",
    tags: ["60s", "music", "groovy", "retro", "fun"],
    description: "Nuansa musik pop 60-an yang ceria dan santai.",
    badge: "Comic",
  },
  {
    id: "mouse_memoirs",
    name: "Mouse Memoirs",
    family: "'Mouse Memoirs', sans-serif",
    category: "comic",
    weights: [400],
    googleFontFamily: "Mouse+Memoirs",
    license: "OFL-1.1",
    tags: ["animated", "quirky", "tall", "vintage_cartoon"],
    description: "Tinggi ramping terinspirasi dari animasi kartun klasik.",
    badge: "Comic",
  },
  {
    id: "rubik_bubbles",
    name: "Rubik Bubbles",
    family: "'Rubik Bubbles', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Rubik+Bubbles",
    license: "OFL-1.1",
    tags: ["bubble", "cartoon", "pop", "fun", "balloon"],
    description: "Efek balon sabun 3D yang sangat menarik perhatian.",
    badge: "Comic",
  },
  {
    id: "sniglet",
    name: "Sniglet",
    family: "'Sniglet', cursive",
    category: "comic",
    weights: [800],
    googleFontFamily: "Sniglet:wght@800",
    license: "OFL-1.1",
    tags: ["cute", "rounded", "kids", "friendly"],
    description: "Sangat ramah dan menggemaskan untuk konten ringan.",
    badge: "Comic",
  },
  {
    id: "carter_one",
    name: "Carter One",
    family: "'Carter One', cursive",
    category: "comic",
    weights: [400],
    googleFontFamily: "Carter+One",
    license: "OFL-1.1",
    tags: ["bold", "friendly", "retro", "signage"],
    description: "Sans kasual tebal dengan kepribadian hangat.",
    badge: "Comic",
  },

  // ----------------------------------------------------
  // RETRO (8 fonts)
  // ----------------------------------------------------
  {
    id: "pacifico",
    name: "Pacifico",
    family: "'Pacifico', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Pacifico",
    license: "OFL-1.1",
    tags: ["surf", "script", "vintage", "50s", "california"],
    description: "Kaligrafi kuas budaya selancar Amerika tahun 50-an.",
    badge: "Retro",
  },
  {
    id: "lobster",
    name: "Lobster",
    family: "'Lobster', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Lobster",
    license: "OFL-1.1",
    tags: ["script", "classic", "bold", "retro", "popular"],
    description: "Skrip retro tebal yang sangat populer untuk judul video.",
    badge: "Retro",
  },
  {
    id: "limelight",
    name: "Limelight",
    family: "'Limelight', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Limelight",
    license: "OFL-1.1",
    tags: ["artdeco", "hollywood", "20s", "cinema", "theatre"],
    description: "Gaya Art Deco teater bioskop era film bisu Hollywood.",
    badge: "Retro",
  },
  {
    id: "monoton",
    name: "Monoton",
    family: "'Monoton', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Monoton",
    license: "OFL-1.1",
    tags: ["neon", "multi-line", "disco", "70s", "futuristic"],
    description: "Garis sejajar bergaya neon disko era 70-80an.",
    badge: "Retro",
  },
  {
    id: "fascinate",
    name: "Fascinate",
    family: "'Fascinate', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Fascinate",
    license: "OFL-1.1",
    tags: ["broadway", "deco", "fancy", "contrast"],
    description: "Kontras tinggi dekoratif panggung broadway klasik.",
    badge: "Retro",
  },
  {
    id: "yesteryear",
    name: "Yesteryear",
    family: "'Yesteryear', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Yesteryear",
    license: "OFL-1.1",
    tags: ["50s", "calligraphy", "chrome", "diner"],
    description: "Kaligrafi miring restoran diner Amerika era 1950.",
    badge: "Retro",
  },
  {
    id: "rye",
    name: "Rye",
    family: "'Rye', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Rye",
    license: "OFL-1.1",
    tags: ["western", "saloon", "rustic", "vintage", "cowboy"],
    description: "Gaya poster koboi Wild West yang gagah.",
    badge: "Retro",
  },
  {
    id: "special_elite",
    name: "Special Elite",
    family: "'Special Elite', cursive",
    category: "retro",
    weights: [400],
    googleFontFamily: "Special+Elite",
    license: "OFL-1.1",
    tags: ["typewriter", "grunge", "vintage", "document", "mystery"],
    description: "Ketik mesin tik manual vintage untuk misteri dan fakta.",
    badge: "Retro",
  },

  // ----------------------------------------------------
  // HANDWRITING (10 fonts)
  // ----------------------------------------------------
  {
    id: "caveat",
    name: "Caveat",
    family: "'Caveat', cursive",
    category: "handwriting",
    weights: [700],
    googleFontFamily: "Caveat:wght@700",
    license: "OFL-1.1",
    tags: ["marker", "casual", "flowing", "story", "personal"],
    description: "Tulisan spidol santai yang natural dan mudah dibaca.",
    badge: "Script",
  },
  {
    id: "kalam",
    name: "Kalam",
    family: "'Kalam', cursive",
    category: "handwriting",
    weights: [700],
    googleFontFamily: "Kalam:wght@700",
    license: "OFL-1.1",
    tags: ["ballpoint", "informal", "clean", "spontaneous"],
    description: "Goresan pena tebal dengan kehangatan catatan tangan.",
    badge: "Script",
  },
  {
    id: "patrick_hand",
    name: "Patrick Hand",
    family: "'Patrick Hand', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Patrick+Hand",
    license: "OFL-1.1",
    tags: ["teacher", "feltpen", "clear", "friendly", "neat"],
    description: "Tulisan spidol rapi dan jelas, cocok untuk edukasi.",
    badge: "Script",
  },
  {
    id: "permanent_marker",
    name: "Permanent Marker",
    family: "'Permanent Marker', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Permanent+Marker",
    license: "OFL-1.1",
    tags: ["bold", "graffiti", "street", "vlog", "heavy"],
    description: "Spidol permanen tebal gaya vlog dan street style.",
    badge: "Script",
  },
  {
    id: "shadows_into_light",
    name: "Shadows Into Light",
    family: "'Shadows Into Light', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Shadows+Into+Light",
    license: "OFL-1.1",
    tags: ["dainty", "expressive", "clean", "aesthetic"],
    description: "Tulisan tangan feminin dan estetik yang anggun.",
    badge: "Script",
  },
  {
    id: "gloria_hallelujah",
    name: "Gloria Hallelujah",
    family: "'Gloria Hallelujah', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Gloria+Hallelujah",
    license: "OFL-1.1",
    tags: ["chalkboard", "fun", "bouncy", "youth"],
    description: "Tulisan papan tulis kapur yang riang dan bersahabat.",
    badge: "Script",
  },
  {
    id: "indie_flower",
    name: "Indie Flower",
    family: "'Indie Flower', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Indie+Flower",
    license: "OFL-1.1",
    tags: ["carefree", "doodle", "relaxed", "lifestyle"],
    description: "Santai dan berjiwa bebas untuk konten lifestyle.",
    badge: "Script",
  },
  {
    id: "architects_daughter",
    name: "Architects Daughter",
    family: "'Architects Daughter', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Architects+Daughter",
    license: "OFL-1.1",
    tags: ["blueprint", "grid", "architect", "sketch"],
    description: "Tulisan gambar arsitek dengan karakter garis tegas.",
    badge: "Script",
  },
  {
    id: "satisfy",
    name: "Satisfy",
    family: "'Satisfy', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Satisfy",
    license: "OFL-1.1",
    tags: ["brush", "signature", "smooth", "elegant_script"],
    description: "Skrip kuas halus yang elegan layaknya tanda tangan.",
    badge: "Script",
  },
  {
    id: "kaushan_script",
    name: "Kaushan Script",
    family: "'Kaushan Script', cursive",
    category: "handwriting",
    weights: [400],
    googleFontFamily: "Kaushan+Script",
    license: "OFL-1.1",
    tags: ["brushstroke", "energetic", "raw", "artistic"],
    description: "Goresan kuas tebal dan dinamis penuh emosi.",
    badge: "Script",
  },

  // ----------------------------------------------------
  // ELEGANT / SERIF (8 fonts)
  // ----------------------------------------------------
  {
    id: "playfair_display",
    name: "Playfair Display",
    family: "'Playfair Display', serif",
    category: "elegant",
    weights: [700, 900],
    googleFontFamily: "Playfair+Display:ital,wght@0,700;0,900;1,700",
    license: "OFL-1.1",
    tags: ["editorial", "vogue", "classic", "luxury", "podcast"],
    description: "Serif majalah fashion mewah dan kutipan podcast berbobot.",
    badge: "Serif",
  },
  {
    id: "abril_fatface",
    name: "Abril Fatface",
    family: "'Abril Fatface', serif",
    category: "elegant",
    weights: [400],
    googleFontFamily: "Abril+Fatface",
    license: "OFL-1.1",
    tags: ["didone", "contrast", "poster", "editorial", "dramatic"],
    description: "Kontras garis tebal-tipis ekstrem era poster abad ke-19.",
    badge: "Serif",
  },
  {
    id: "dm_serif_display",
    name: "DM Serif Display",
    family: "'DM Serif Display', serif",
    category: "elegant",
    weights: [400],
    googleFontFamily: "DM+Serif+Display",
    license: "OFL-1.1",
    tags: ["modern", "editorial", "luxury", "subtle"],
    description: "Serif kontemporer dengan kurva anggun dan modern.",
    badge: "Serif",
  },
  {
    id: "cormorant_garamond",
    name: "Cormorant Garamond",
    family: "'Cormorant Garamond', serif",
    category: "elegant",
    weights: [700],
    googleFontFamily: "Cormorant+Garamond:wght@700",
    license: "OFL-1.1",
    tags: ["traditional", "delicate", "book", "poetry", "history"],
    description: "Serif sastra klasik yang sangat megah dan terhormat.",
    badge: "Serif",
  },
  {
    id: "cinzel",
    name: "Cinzel",
    family: "'Cinzel', serif",
    category: "elegant",
    weights: [700],
    googleFontFamily: "Cinzel:wght@700",
    license: "OFL-1.1",
    tags: ["roman", "monumental", "cinematic", "epic", "history"],
    description: "Pahatan batu Romawi kuno untuk trailer sinematik dan sejarah.",
    badge: "Serif",
  },
  {
    id: "prata",
    name: "Prata",
    family: "'Prata', serif",
    category: "elegant",
    weights: [400],
    googleFontFamily: "Prata",
    license: "OFL-1.1",
    tags: ["fashion", "didot", "refined", "beauty"],
    description: "Didone elegan dengan teardrop terminal yang memikat.",
    badge: "Serif",
  },
  {
    id: "bodoni_moda",
    name: "Bodoni Moda",
    family: "'Bodoni Moda', serif",
    category: "elegant",
    weights: [700],
    googleFontFamily: "Bodoni+Moda:ital,opsz,wght@0,6..96,700;1,6..96,700",
    license: "OFL-1.1",
    tags: ["haute_couture", "extreme_contrast", "glamour"],
    description: "Kemewahan haute-couture dengan kontras dramatis.",
    badge: "Serif",
  },
  {
    id: "yeseva_one",
    name: "Yeseva One",
    family: "'Yeseva One', serif",
    category: "elegant",
    weights: [400],
    googleFontFamily: "Yeseva+One",
    license: "OFL-1.1",
    tags: ["feminine", "graceful", "curvy", "display"],
    description: "Bentuk serif anggun dan melengkung lembut.",
    badge: "Serif",
  },

  // ----------------------------------------------------
  // CONDENSED / NEWS (8 fonts)
  // ----------------------------------------------------
  {
    id: "oswald",
    name: "Oswald",
    family: "'Oswald', sans-serif",
    category: "news",
    weights: [500, 700],
    googleFontFamily: "Oswald:wght@500;700",
    license: "OFL-1.1",
    tags: ["gothic", "tall", "compact", "headline", "news"],
    description: "Ramping dan tinggi, menghemat ruang horizontal pada kalimat panjang.",
    badge: "News",
  },
  {
    id: "roboto_condensed",
    name: "Roboto Condensed",
    family: "'Roboto Condensed', sans-serif",
    category: "news",
    weights: [400, 700],
    googleFontFamily: "Roboto+Condensed:wght@400;700",
    license: "OFL-1.1",
    tags: ["clean", "ui", "news", "broadcast", "neutral"],
    description: "Gaya siaran berita TV yang netral dan sangat terbaca.",
    badge: "News",
  },
  {
    id: "teko",
    name: "Teko",
    family: "'Teko', sans-serif",
    category: "news",
    weights: [600, 700],
    googleFontFamily: "Teko:wght@600;700",
    license: "OFL-1.1",
    tags: ["narrow", "sport", "speed", "score", "bold"],
    description: "Sangat tinggi dan ramping, gaya score board olahraga & breaking news.",
    badge: "News",
  },
  {
    id: "saira_condensed",
    name: "Saira Condensed",
    family: "'Saira Condensed', sans-serif",
    category: "news",
    weights: [600, 800],
    googleFontFamily: "Saira+Condensed:wght@600;800",
    license: "OFL-1.1",
    tags: ["athletic", "tight", "broadcast", "solid"],
    description: "Gaya tipografi grafis siaran esport dan dokumenter.",
    badge: "News",
  },
  {
    id: "fjalla_one",
    name: "Fjalla One",
    family: "'Fjalla One', sans-serif",
    category: "news",
    weights: [400],
    googleFontFamily: "Fjalla+One",
    license: "OFL-1.1",
    tags: ["nordic", "headline", "poster", "solid", "display"],
    description: "Headline Skandinavia yang kokoh dan berkarakter kuat.",
    badge: "News",
  },
  {
    id: "league_gothic",
    name: "League Gothic",
    family: "'League Gothic', sans-serif",
    category: "news",
    weights: [400],
    googleFontFamily: "League+Gothic",
    license: "OFL-1.1",
    tags: ["classic", "revival", "newspaper", "historic"],
    description: "Klasik surat kabar awal abad ke-20 dengan wibawa jurnalistik.",
    badge: "News",
  },
  {
    id: "antonio",
    name: "Antonio",
    family: "'Antonio', sans-serif",
    category: "news",
    weights: [700],
    googleFontFamily: "Antonio:wght@700",
    license: "OFL-1.1",
    tags: ["modern_condensed", "signage", "ad", "bold"],
    description: "Condensed modern untuk teks hook ringkas dan padat.",
    badge: "News",
  },
  {
    id: "big_shoulders_display",
    name: "Big Shoulders Display",
    family: "'Big Shoulders Display', sans-serif",
    category: "news",
    weights: [700, 900],
    googleFontFamily: "Big+Shoulders+Display:wght@700;900",
    license: "OFL-1.1",
    tags: ["chicago", "tall", "impactful", "urban"],
    description: "Terinspirasi dari desain poster kota Chicago yang gagah.",
    badge: "News",
  },

  // ----------------------------------------------------
  // MODERN / CLEAN (6 fonts)
  // ----------------------------------------------------
  {
    id: "inter",
    name: "Inter",
    family: "'Inter', sans-serif",
    category: "modern",
    weights: [400, 600, 800],
    googleFontFamily: "Inter:wght@400;600;800",
    license: "OFL-1.1",
    tags: ["interface", "neutral", "legible", "modern", "ui"],
    description: "Keterbacaan nomor satu di semua resolusi layar.",
    badge: "Clean",
  },
  {
    id: "montserrat",
    name: "Montserrat",
    family: "'Montserrat', sans-serif",
    category: "modern",
    weights: [400, 700, 900],
    googleFontFamily: "Montserrat:wght@400;700;900",
    license: "OFL-1.1",
    tags: ["geometric", "urban", "modern", "stylish", "popular"],
    description: "Geometris perkotaan modern yang serbaguna untuk segala konten.",
    badge: "Clean",
  },
  {
    id: "poppins",
    name: "Poppins",
    family: "'Poppins', sans-serif",
    category: "modern",
    weights: [600, 800],
    googleFontFamily: "Poppins:wght@600;800",
    license: "OFL-1.1",
    tags: ["geometric", "friendly", "clean", "youtube"],
    description: "Bentuk bulat geometris yang hangat dan sangat digemari kreator.",
    badge: "Clean",
  },
  {
    id: "plus_jakarta_sans",
    name: "Plus Jakarta Sans",
    family: "'Plus Jakarta Sans', sans-serif",
    category: "modern",
    weights: [600, 800],
    googleFontFamily: "Plus+Jakarta+Sans:wght@600;800",
    license: "OFL-1.1",
    tags: ["contemporary", "indonesia", "corporate", "fresh"],
    description: "Kebanggaan tipografi Indonesia, modern, bersih, dan segar.",
    badge: "Clean",
  },
  {
    id: "outfit",
    name: "Outfit",
    family: "'Outfit', sans-serif",
    category: "modern",
    weights: [600, 800],
    googleFontFamily: "Outfit:wght@600;800",
    license: "OFL-1.1",
    tags: ["tech", "brand", "sleek", "futuristic"],
    description: "Sans geometris futuristik yang sleek untuk tech dan startup.",
    badge: "Clean",
  },
  {
    id: "rubik",
    name: "Rubik",
    family: "'Rubik', sans-serif",
    category: "modern",
    weights: [600, 800],
    googleFontFamily: "Rubik:wght@600;800",
    license: "OFL-1.1",
    tags: ["soft", "rounded", "subtle", "contemporary"],
    description: "Bentuk sudut membulat halus yang nyaman di mata.",
    badge: "Clean",
  },
];

const LEGACY_FONT_MAP: Record<string, string> = {
  bold_sans: "'Anton', 'Arial Black', sans-serif",
  elegant_serif: "'Playfair Display', Georgia, serif",
  modern_rounded: "'Fredoka', 'Baloo 2', sans-serif",
  condensed_news: "'Oswald', 'Roboto Condensed', sans-serif",
  playful: "'Caveat', 'Patrick Hand', cursive",
  clean_sans: "'Inter', sans-serif",
};

export function getFontById(id: string): FontDefinition | undefined {
  const normalized = id.toLowerCase().replace(/[\s-]+/g, "_");
  return FONT_CATALOG.find((f) => f.id === normalized);
}

export function getFontByFamily(familyStr: string): FontDefinition | undefined {
  if (!familyStr) return undefined;
  const clean = familyStr.replace(/['"]/g, "").toLowerCase();
  return FONT_CATALOG.find((f) => {
    const fClean = f.family.replace(/['"]/g, "").toLowerCase();
    return (
      clean.includes(f.name.toLowerCase()) ||
      clean.includes(f.id.replace(/_/g, " ")) ||
      fClean.includes(clean)
    );
  });
}

export function resolveFontFamily(fontKeyOrFamily: string | undefined): string {
  if (!fontKeyOrFamily) return "'Inter', sans-serif";
  if (LEGACY_FONT_MAP[fontKeyOrFamily]) {
    return LEGACY_FONT_MAP[fontKeyOrFamily];
  }
  const match = getFontById(fontKeyOrFamily) || getFontByFamily(fontKeyOrFamily);
  if (match) {
    return match.family;
  }
  return fontKeyOrFamily;
}

export function searchFonts(
  query: string,
  category: FontCategory = "all",
): FontDefinition[] {
  const q = query.trim().toLowerCase();
  return FONT_CATALOG.filter((font) => {
    const matchesCategory = category === "all" || font.category === category;
    if (!matchesCategory) return false;
    if (!q) return true;

    return (
      font.name.toLowerCase().includes(q) ||
      font.id.toLowerCase().includes(q) ||
      font.category.toLowerCase().includes(q) ||
      (font.description && font.description.toLowerCase().includes(q)) ||
      (font.badge && font.badge.toLowerCase().includes(q)) ||
      font.tags.some((tag) => tag.toLowerCase().includes(q))
    );
  });
}
